### ISSUE TITLE
tensorflow version requirement 

### ISSUE THREAD

**Issue by HarrisonLL** [nikicc/twitter-emotion-recognition#22]
Hello,

I have run the demo.py on google colab many times. It produces the error as following. The version used here is Keras 2.4.3 and tensorflow 2.4.1. Also, when I change the version of Keras to 1.1.0. It always produces package incompatible issue like " AttributeError: module ‘tensorflow’ has no attribute ‘placeholder’". So I wonder if the keras to use is 1.1.0, then what is a good tensorflow version? If I can use a higher version of keras, how can solve the issue?

The error is here:
2021-03-23 17:27:15.925728: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
Traceback (most recent call last):
  File "twitter-emotion-recognition/demo.py", line 12, in <module>
    model = EmotionPredictor(classification='ekman', setting='mc', use_unison_model=True)
  File "/content/twitter-emotion-recognition/emotion_predictor.py", line 30, in __init__
    self.model = self._get_model()
  File "/content/twitter-emotion-recognition/emotion_predictor.py", line 42, in _get_model
    return load_model(self._loaded_model_filename)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/saving/save.py", line 207, in load_model
    compile)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/saving/hdf5_format.py", line 184, in load_model_from_hdf5
    custom_objects=custom_objects)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/saving/model_config.py", line 64, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/layers/serialization.py", line 177, in deserialize
    printable_module_name='layer')
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/utils/generic_utils.py", line 358, in deserialize_keras_object
    list(custom_objects.items())))
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py", line 2262, in from_config
    config, custom_objects=custom_objects)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/functional.py", line 669, in from_config
    config, custom_objects)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/functional.py", line 1275, in reconstruct_from_config
    process_layer(layer_data)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/functional.py", line 1257, in process_layer
    layer = deserialize_layer(layer_data, custom_objects=custom_objects)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/layers/serialization.py", line 177, in deserialize
    printable_module_name='layer')
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/utils/generic_utils.py", line 360, in deserialize_keras_object
    return cls.from_config(cls_config)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 720, in from_config
    return cls(**config)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/input_layer.py", line 118, in __init__
    raise ValueError('Unrecognized keyword arguments:', kwargs.keys())
ValueError: ('Unrecognized keyword arguments:', dict_keys(['input_dtype']))

**Comment by slankas** [comment]
I've experienced this same problem.  Tensorflow actually isn't required.  There's a slight difference between the Jupyter notebook and demo app.  Add these two lines to the top of demo.py:
```
import os;
os.environ['KERAS_BACKEND'] = 'theano'
```

**Comment by nikicc** [comment]
Yes, as @slankas suggested, the code cannot work with tensorflow, it requires Theano as the backend. Regarding the versions, check the [requirements.txt file](https://github.com/nikicc/twitter-emotion-recognition/blob/master/requirements.txt) — if you use exactly those versions it should work.

**Comment by slankas** [comment]
Here's the exact steps I used on pretty much a base Ubuntu 18.04 virtual machine:
```
sudo apt-get install -y python3-venv
sudo apt-get install -y python3-dev
mkdir emotion
cd emotion
python3 -m venv .
source bin/activate
git clone https://github.com/nikicc/twitter-emotion-recognition.git
cd twitter-emotion-recognition
pip install --upgrade pip
pip install wheel
pip install --upgrade setuptools
pip install -r requirements.txt

### Edit demo.py.  add the following lines at the top of the file. The uncommented line should do this ...
### import os;
### os.environ['KERAS_BACKEND'] = 'theano'
cat <(echo -e "import os;\nos.environ['KERAS_BACKEND'] = 'theano'\n\n") demo.py > new.py

python new.py
```

**Comment by HarrisonLL** [comment]
Resolved the issue. Thanks!!!

**Comment by nikicc** [comment]
@LidingLi happy to hear that 👍
