### ISSUE TITLE
Binder fails to start

### ISSUE THREAD

**Issue by maciejskorski** [nikicc/twitter-emotion-recognition#36]
With error logs:
```
Waiting for build to start...
Picked Git content provider.
Cloning into '/tmp/repo2docker4odte8kr'...
HEAD is now at 7af2a0b Bump pyyaml from 5.1 to 5.4 (#24)
Python version unspecified, using current default Python version 3.10. This will change in the future.Building conda environment for python=3.10
Using PythonBuildPack builder
Step 1/50 : FROM docker.io/library/buildpack-deps:jammy
 ---> 9336076452fd
Step 2/50 : ENV DEBIAN_FRONTEND=noninteractive
 ---> Using cache
 ---> d1ff7591f21e
Step 3/50 : RUN apt-get -qq update &&     apt-get -qq install --yes --no-install-recommends locales > /dev/null &&     apt-get -qq purge &&     apt-get -qq clean &&     rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> aeae490ecabe
Step 4/50 : RUN echo "en_US.UTF-8 UTF-8" > /etc/locale.gen &&     locale-gen
 ---> Using cache
 ---> c0914662da05
Step 5/50 : ENV LC_ALL=en_US.UTF-8     LANG=en_US.UTF-8     LANGUAGE=en_US.UTF-8
 ---> Using cache
 ---> a11237220a9f
Step 6/50 : ENV SHELL=/bin/bash
 ---> Using cache
 ---> e645c5f56303
Step 7/50 : ARG NB_USER
 ---> Using cache
 ---> e53aff3ab4a3
Step 8/50 : ARG NB_UID
 ---> Using cache
 ---> 4e68be02d867
Step 9/50 : ENV USER=${NB_USER}     HOME=/home/${NB_USER}
 ---> Using cache
 ---> f5ca8162d797
Step 10/50 : RUN groupadd         --gid ${NB_UID}         ${NB_USER} &&     useradd         --comment "Default user"         --create-home         --gid ${NB_UID}         --no-log-init         --shell /bin/bash         --uid ${NB_UID}         ${NB_USER}
 ---> Using cache
 ---> 41d8a66c2107
Step 11/50 : RUN apt-get -qq update &&     apt-get -qq install --yes --no-install-recommends        gettext-base        less        unzip        > /dev/null &&     apt-get -qq purge &&     apt-get -qq clean &&     rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> fa888af135ac
Step 12/50 : EXPOSE 8888
 ---> Using cache
 ---> 52a9553fc60c
Step 13/50 : ENV APP_BASE=/srv
 ---> Using cache
 ---> 167136613824
Step 14/50 : ENV CONDA_DIR=${APP_BASE}/conda
 ---> Using cache
 ---> 51c913cf1f8c
Step 15/50 : ENV NB_PYTHON_PREFIX=${CONDA_DIR}/envs/notebook
 ---> Using cache
 ---> 1d48fdbdebf7
Step 16/50 : ENV NPM_DIR=${APP_BASE}/npm
 ---> Using cache
 ---> df609e219079
Step 17/50 : ENV NPM_CONFIG_GLOBALCONFIG=${NPM_DIR}/npmrc
 ---> Using cache
 ---> e0fdfa71524a
Step 18/50 : ENV NB_ENVIRONMENT_FILE=/tmp/env/environment.lock
 ---> Using cache
 ---> 883a3e26a174
Step 19/50 : ENV MAMBA_ROOT_PREFIX=${CONDA_DIR}
 ---> Using cache
 ---> 64e780b6bc49
Step 20/50 : ENV MAMBA_EXE=${CONDA_DIR}/bin/mamba
 ---> Using cache
 ---> 3ca7557747a7
Step 21/50 : ENV CONDA_PLATFORM=linux-64
 ---> Using cache
 ---> 2c87249fd8ec
Step 22/50 : ENV KERNEL_PYTHON_PREFIX=${NB_PYTHON_PREFIX}
 ---> Using cache
 ---> 2a76bd4920df
Step 23/50 : ENV PATH=${NB_PYTHON_PREFIX}/bin:${CONDA_DIR}/bin:${NPM_DIR}/bin:${PATH}
 ---> Using cache
 ---> 4f8eff94acaa
Step 24/50 : COPY --chown=1000:1000 build_script_files/-2fusr-2flib-2fpython3-2e10-2fsite-2dpackages-2frepo2docker-2fbuildpacks-2fconda-2factivate-2dconda-2esh-44e764 /etc/profile.d/activate-conda.sh
 ---> Using cache
 ---> 2cb7e8b49550
Step 25/50 : COPY --chown=1000:1000 build_script_files/-2fusr-2flib-2fpython3-2e10-2fsite-2dpackages-2frepo2docker-2fbuildpacks-2fconda-2fenvironment-2epy-2d3-2e10-2dlinux-2d64-2elock-388e0b /tmp/env/environment.lock
 ---> Using cache
 ---> 4647fb9682a9
Step 26/50 : COPY --chown=1000:1000 build_script_files/-2fusr-2flib-2fpython3-2e10-2fsite-2dpackages-2frepo2docker-2fbuildpacks-2fconda-2finstall-2dbase-2denv-2ebash-e5509f /tmp/install-base-env.bash
 ---> Using cache
 ---> 5c1f22211237
Step 27/50 : RUN TIMEFORMAT='time: %3R' bash -c 'time /tmp/install-base-env.bash' && rm -rf /tmp/install-base-env.bash /tmp/env
 ---> Using cache
 ---> e75e50715333
Step 28/50 : RUN mkdir -p ${NPM_DIR} && chown -R ${NB_USER}:${NB_USER} ${NPM_DIR}
 ---> Using cache
 ---> 906c5f16991a
Step 29/50 : USER root
 ---> Using cache
 ---> afb51a5095b5
Step 30/50 : ARG REPO_DIR=${HOME}
 ---> Using cache
 ---> 05814ae0d08c
Step 31/50 : ENV REPO_DIR=${REPO_DIR}
 ---> Using cache
 ---> c59680602fe8
Step 32/50 : RUN if [ ! -d "${REPO_DIR}" ]; then         /usr/bin/install -o ${NB_USER} -g ${NB_USER} -d "${REPO_DIR}";     fi
 ---> Using cache
 ---> 6564eb671567
Step 33/50 : WORKDIR ${REPO_DIR}
 ---> Using cache
 ---> 8ac13bf1d519
Step 34/50 : RUN chown ${NB_USER}:${NB_USER} ${REPO_DIR}
 ---> Using cache
 ---> f685e90965a1
Step 35/50 : ENV PATH=${HOME}/.local/bin:${REPO_DIR}/.local/bin:${PATH}
 ---> Using cache
 ---> 7b4171a07b72
Step 36/50 : ENV CONDA_DEFAULT_ENV=${KERNEL_PYTHON_PREFIX}
 ---> Using cache
 ---> 8507698d2dd4
Step 37/50 : COPY --chown=1000:1000 src/requirements.txt ${REPO_DIR}/requirements.txt
 ---> e50988b4d98a
Step 38/50 : USER ${NB_USER}
 ---> Running in ba9575eda0b5
Removing intermediate container ba9575eda0b5
 ---> 54f1979258a4
Step 39/50 : RUN ${KERNEL_PYTHON_PREFIX}/bin/pip install --no-cache-dir -r "requirements.txt"
 ---> Running in 50156477c7f3
Collecting h5py==2.9.0 (from -r requirements.txt (line 1))
  Downloading h5py-2.9.0.tar.gz (287 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 287.9/287.9 kB 14.1 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting Keras==1.1.0 (from -r requirements.txt (line 2))
  Downloading Keras-1.1.0.tar.gz (150 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 150.5/150.5 kB 24.3 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting numpy==1.16.0 (from -r requirements.txt (line 3))
  Downloading numpy-1.16.0.zip (5.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 31.7 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting pandas==0.24.1 (from -r requirements.txt (line 4))
  Downloading pandas-0.24.1.tar.gz (11.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.8/11.8 MB 39.7 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      /tmp/pip-install-z2h0gjjc/pandas_7e873731d172482c899c7d67931eade3/setup.py:12: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
        import pkg_resources
      Traceback (most recent call last):
        File "/srv/conda/envs/notebook/lib/python3.10/site-packages/pkg_resources/__init__.py", line 402, in get_provider
          module = sys.modules[moduleOrReq]
      KeyError: 'numpy'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-z2h0gjjc/pandas_7e873731d172482c899c7d67931eade3/setup.py", line 732, in <module>
          ext_modules=maybe_cythonize(extensions, compiler_directives=directives),
        File "/tmp/pip-install-z2h0gjjc/pandas_7e873731d172482c899c7d67931eade3/setup.py", line 475, in maybe_cythonize
          numpy_incl = pkg_resources.resource_filename('numpy', 'core/include')
        File "/srv/conda/envs/notebook/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1213, in resource_filename
          return get_provider(package_or_requirement).get_resource_filename(
        File "/srv/conda/envs/notebook/lib/python3.10/site-packages/pkg_resources/__init__.py", line 404, in get_provider
          __import__(moduleOrReq)
      ModuleNotFoundError: No module named 'numpy'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Removing intermediate container 50156477c7f3
The command '/bin/sh -c ${KERNEL_PYTHON_PREFIX}/bin/pip install --no-cache-dir -r "requirements.txt"' returned a non-zero code: 1
```

**Comment by nikicc** [comment]
Hey @maciejskorski! It seem like `numpy` is missing? Did you install all of the dependencies as specified in the [requirements.txt](https://github.com/nikicc/twitter-emotion-recognition/blob/master/requirements.txt) file? Make sure that `numpy==1.16.0` is installed.
